#!/bin/bash

set -o errexit
set -o nounset

while [[ $(kubectl get pods -l app=springboot-service-a -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "waiting for pod" && sleep 1; done