name: Build and Test

on:
  push:
    branches:
      - feature-ms-davidsilva-cicd  # Cambiar esto si tu rama principal se llama de manera diferente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build project
        run: ./gradlew build
