name: Build and Deploy

on:
  push:
    branches:
      - feature-ms-davidsilva-cicd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11' # Change to the appropriate Java version

    - name: Build and package service-a
      run: mvn clean package spring-boot:build-image -pl service-a

    - name: Build and package service-b
      run: mvn clean package spring-boot:build-image -pl service-b

    - name: Build and package service-c
      run: mvn clean package spring-boot:build-image -pl service-c

    - name: Build Gradle project
      run: |
        ./gradlew clean build bootBuildImage
      working-directory: ${{ github.workspace }}

    - name: Start Docker containers
      run: |
        docker run -d -p 8081:8080 -e spring.profiles.active=prod -e serviceb.url=http://localhost:8082 -e servicec.url=http://localhost:8083 $DOCKER_USER_NAME$/spring-multi-module-service-service-a
        docker run -d -p 8082:8080 -e spring.profiles.active=prod $DOCKER_USER_NAME$/spring-multi-module-service-service-b
        docker run -d -p 8083:8080 -e spring.profiles.active=prod $DOCKER_USER_NAME$/spring-multi-module-service-service-c
      env:
        DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME }} # You should store your Docker username as a secret in your repository

    - name: Wait for containers to start
      run: sleep 10

    - name: Test service endpoints
      run: |
        curl http://localhost:8081/greeting
        curl http://localhost:8082/greeting
        curl http://localhost:8083/greeting

    - name: Check Docker images
      run: docker images | grep spring-multi-module

    - name: Deploy service-a
      run: |
        docker push $DOCKER_USER_NAME$/spring-multi-module-service-service-a
        # You may need to deploy service-b and service-c in a similar manner

    - name: Deploy to Production (if needed)
      # Add steps for deploying to production, if necessary
