name: Build and Deploy Services

on:
  push:
    branches:
      - feature-ms-davidsilva-cicd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build Gradle projects
      run: |
        ./gradlew clean build bootBuildImage

    - name: Start service-a
      run: |
        java -jar service-a/target/service-a-0.0.1-SNAPSHOT.jar &

    - name: Start service-b
      run: |
        java -jar service-b/target/service-b-0.0.1-SNAPSHOT.jar &

    - name: Start service-c
      run: |
        java -jar service-c/target/service-c-0.0.1-SNAPSHOT.jar &

    - name: Wait for services to start
      run: sleep 10 # Adjust the sleep duration as needed to allow services to start.

    - name: Test services with curl
      run: |
        curl http://localhost:8081/greeting
        curl http://localhost:8082/greeting
        curl http://localhost:8083/greeting

    - name: List Docker images
      run: docker images | grep spring-multi-module

    - name: Deploy services using Docker
      run: |
        docker run -d -p 8081:8080 -e spring.profiles.active=prod -e serviceb.url=http://<HOST_IP>:8082 -e servicec.url=http://<HOST_IP>:8083 $DOCKER_USER_NAME/spring-multi-module-service-service-a
        docker run -d -p 8082:8080 -e spring.profiles.active=prod $DOCKER_USER_NAME/spring-multi-module-service-service-b
        docker run -d -p 8083:8080 -e spring.profiles.active=prod $DOCKER_USER_NAME/spring-multi-module-service-service-c
