name: Checkout Workflow

on:
  push:
    branches:
      - feature-ms-davidsilva-cicd  # Cambia 'main' al nombre de tu rama principal si es diferente

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
