name: Containerize and Deploy

on:
  push:
    branches:
      - feature-ms-davidsilva-cicd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List Maven modules
        run: mvn help:evaluate -Dexpression=project.modules

      - name: Build and create Docker images
        run: mvn clean package spring-boot:build-image

      - name: Execute Maven goal on specific module
        run: mvn clean spring-boot:run -pl service-a
