name: Build and Deploy Services

on:
  push:
    branches:
      - feature-ms-davidsilva-cicd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build and package Maven modules
      run: |
        mvn help:evaluate -Dexpression=project.modules
        mvn clean package spring-boot:build-image -pl service-a
        rootProject.name='spring-multi-module-service'
        include 'service-a'
        include 'service-b'
        include 'service-c'

    - name: Build Gradle projects
      run: |
        ./gradlew clean build bootBuildImage
        ./gradlew clean :service-a:build :service-a:bootBuildImage

    - name: Start service-a
      run: |
        java -jar service-a/target/service-a-0.0.1-SNAPSHOT.jar &

    - name: Start service-b
      run: |
        java -jar service-b/target/service-b-0.0.1-SNAPSHOT.jar &

    - name: Start service-c
      run: |
        java -jar service-c/target/service-c-0.0.1-SNAPSHOT.jar &

    - name: Wait for services to start
      run: sleep 10 # Adjust the sleep duration as needed to allow services to start.

    - name: Test services with curl
      run: |
        curl http://localhost:8081/greeting
        curl http://localhost:8082/greeting
        curl http://localhost:8083/greeting
