name: Dockerize Maven Modules

on:
  push:
    branches:
      - feature-ms-davidsilva-cicd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build and create Docker images
      run: |
        mvn clean package spring-boot:build-image
