name: Deploy Docker Containers

on:
  push:
    branches:
      - feature-ms-davidsilva-cicd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo apt-get install -y docker-compose

    - name: Build and Deploy Docker containers
      run: |
        docker-compose up -d
