name: Build Maven and Gradle

on:
  push:
    branches:
      - feature-ms-davidsilva-cicd
jobs:
  build-maven:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package

  build-gradle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build
