name: SonarCloud Analysis

on:
  push:
    branches:
      - feature-ms-davidsilva-cicd # Cambia "main" por el nombre de tu rama principal

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Cambia "11" si necesitas una versión diferente de Java
        distribution: 'adopt'

    - name: Run SonarCloud analysis
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

