name: Automatic Code Analysis

on:
  push:
    branches:
      - feature-ms-davidsilva-cicd

jobs:
  analyze-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Super-Linter
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: "true"
