name: Escaneo Automático de Vulnerabilidades

on:
  push:
    branches:
      - feature-ms-davidsilva-cicd

jobs:
  vulnerability_scanning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout de código
      uses: actions/checkout@v2

    - name: Escaneo automático de vulnerabilidades
      uses: securityscan/security-scan-action@v1

    - name: Mostrar resultados del escaneo
      run: cat security-scan-results.txt




