
name: Automatic Code Analysis

on:
  push:
    branches:
      - feature-ms-davidsilva-cicd

jobs:
  analyze-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Build Docker image
      run: |
        docker build -t code-analysis-image .
        docker run --rm code-analysis-image

