name: Análisis SonarQube

on:
  push:
    branches:
      - feature-ms-davidsilva-cicd

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Levantar contenedor SonarQube
        uses: docker/compose-action@v1
        with:
          compose-file: docker-compose.yml
          compose-options: -f docker-compose.yml up -d

      - name: Configurar SonarQube
        run: |
          sleep 30 # Esperar 30 segundos para que el contenedor SonarQube se inicie correctamente
          sonar-scanner -Dsonar.projectKey=my-project -Dsonar.sources=. -Dsonar.dependencyCheck.enabled=true -Dsonar.host.url=http://localhost:9000 -Dsonar.login=admin -Dsonar.password=admin

      - name: Detener y eliminar contenedor SonarQube
        uses: docker/compose-action@v1
        with:
          compose-file: docker-compose.yml
          compose-options: -f docker-compose.yml down
