name: Dependency Vulnerability Analysis

on:
  push:
    branches:
      - feature-ms-davidsilva-cicd

jobs:
  dependency_vulnerability_analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Run vulnerability analysis
      run: |
        ./mvnw dependency-check:check  # Cambia "./mvnw" si utilizas otro comando para construir tu proyecto



