name: Build and Analyze with SonarQube

on:
  push:
    branches:
      - feature-ms-davidsilva-cicd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean verify

      - name: SonarQube analysis
        uses: sonarsource/sonarqube-scan-action@v1
        with:
          projectBaseDir: .

        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.20-101/x64
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

